<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>UCustomBundlerAPI</AssemblyName>
    <Description>A Library for Bundling Assets for Unity</Description>
    <Version>0.0.1</Version>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup>
    <RestoreSources>$(RestoreSources);https://api.nuget.org/v3/index.json;https://nuget.bepinex.dev/v3/index.json</RestoreSources>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>UCustomBundlerAPI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" IncludeAssets="compile" />
    <PackageReference Include="UnityEngine.Modules" Version="2021.3.33" IncludeAssets="compile" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
    <PackageReference Include="System.IO.Compression" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Build\" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy /Y &quot;$(TargetDir)$(ProjectName).dll&quot; &quot;$(ProjDir)Build&quot; &#xD;&#xA;" />
  </Target>

</Project>
